name: Keep Render Alive

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # lets you run it manually too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service
        run: |
          echo "Pinging artisanverse..."
          curl -s -o /dev/null -w "%{http_code}" https://artisanverse-db0b.onrender.com/
